# Generated by Django 6.0.7 on 2026-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='membros',
        ),
    ]
