# Generated by Django 6.0.7 on 2026-08-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0002_remove_grupo_membros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='criador',
        ),
    ]
