# Generated by Django 6.0.7 on 2026-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0003_remove_grupo_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantegrupo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
