# Generated by Django 6.0.7 on 2026-08-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0004_alter_participantegrupo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='participante_grupo',
            new_name='participante_grupo_pagador',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='despesa_paga',
            new_name='valor_despesa',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='pagador',
        ),
        migrations.AddField(
            model_name='despesa',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participacaodespesa',
            name='valor_devido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
