# Generated by Django 6.0.7 on 2026-08-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0005_rename_participante_grupo_pagamento_participante_grupo_pagador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_criadas', to='app_divide.participantegrupo'),
        ),
    ]
