# Generated by Django 6.0.7 on 2026-08-21 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0006_alter_despesa_criador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='criado_por',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='criador_grupo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
