# Generated by Django 6.0.7 on 2026-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0007_grupo_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
