# Generated by Django 6.0.7 on 2026-09-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0008_alter_grupo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='valor_despesa',
            new_name='despesa',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criador_despesas', to='app_divide.participantegrupo'),
        ),
    ]
