# Generated by Django 6.0.7 on 2026-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0009_rename_valor_despesa_pagamento_despesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_paga', to='app_divide.despesa'),
        ),
    ]
