# Generated by Django 6.0.7 on 2026-09-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0010_alter_pagamento_despesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='participante_grupo_pagador',
            new_name='pagador',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_despesa', to='app_divide.grupo'),
        ),
    ]
