# Generated by Django 6.0.7 on 2026-09-12 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0011_rename_participante_grupo_pagador_pagamento_pagador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_paga', to='app_divide.despesa'),
        ),
    ]
