# Generated by Django 6.0.7 on 2026-09-18 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0012_alter_pagamento_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
