# Generated by Django 6.0.7 on 2026-09-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_divide', '0013_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_paga', to='app_divide.despesa'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pagador',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='participante_grupo', to='app_divide.participantegrupo'),
            preserve_default=False,
        ),
    ]
