# Generated by Django 6.0.7 on 2026-07-31 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_grupos', '0002_rename_grupos_grupo_participantegrupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_despesa', models.DateField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='app_grupos.grupo')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_pagas', to='app_grupos.participantegrupo')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='app_despesas.despesa')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_participadas', to='app_grupos.participantegrupo')),
            ],
        ),
    ]
